---
- name: Configure Nginx on Auto Scaling Group instances
  hosts: tag_Name__Zantac_Inc_Web_Server
  become: true
  vars:
    nginx_port: 8080
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
      become: true

    - name: Deploy Nginx configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      become: true

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: true
